services:
  nginx:
    image: nginx:alpine
    container_name: stand-nginx
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - stand-network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stand-backend
    expose:
      - "8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/app:/app/app
    networks:
      - stand-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stand-frontend
    expose:
      - "5173"
    environment:
      - VITE_API_URL=https://localhost
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stand-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  stand-network:
    driver: bridge
