services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stand-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      # Read-only mount - container host dosyalarına yazamaz
      - ./backend/app:/app/app:ro
      # YOLO model dosyaları için kalıcı volume
      - yolo_models:/app/models
    networks:
      - stand-network
    restart: unless-stopped
    # Root user - model dosyasını volume'a yazabilmek için
    user: "0:0"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stand-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stand-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  stand-network:
    driver: bridge

volumes:
  yolo_models:
    driver: local
