services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: stand-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./backend/app:/app/app
    networks:
      - stand-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stand-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - stand-network
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

networks:
  stand-network:
    driver: bridge
